###Fetch al recent tacos
GET localhost:8080/data-api/tacos?recent

###Fetch taco by id
GET localhost:8080/data-api/tacos/1

###Fetch taco by id which is null
GET localhost:8080/api/tacos/18

###Fetch ingredients
GET localhost:8080/data-api/ingredients

###Fetch ingredient flour tortilla
GET http://localhost:8080/data-api/ingredients/FLTO

###Fetch tacos
GET http://localhost:8080/data-api/tacos

###Fetch tacoes
GET http://localhost:8080/data-api/tacoes

###Lists links for all exposed endpoints
GET http://localhost:8080/data-api

###Fetch first page of tacos where the page size is 5
GET http://localhost:8080/data-api/tacos?size=5

###Fetch second page of tacos by adding the page parameter
GET http://localhost:8080/data-api/tacos?size=5&page=0

###Ann new ingredient
# curl localhost:8080/api/ingredients
#  -H"Content-type: application/json"
#  -d'{"id":"FISH","name":"Stinky Fish", "type":"PROTEIN"}'
POST localhost:8080/api/ingredients
Content-Type: application/json

{
  "id": "FISH",
  "name": "Stinky Fish",
  "type": "PROTEIN"
}

###
# curl localhost:8080/api/ingredients/GRBF -X DELETE
DELETE localhost:8080/api/ingredients/GRBF

###
# curl localhost:8080/ingredients
#  -H"Content-type: application/json"
#  -d'{"id":"FISH","name":"Stinky Fish", "type":"PROTEIN"}'
#  -u admin:l3tm31n
POST localhost:8080/ingredients
Authorization: Basic admin l3tm31n
Content-Type: application/json

{
  "id": "FISH",
  "name": "Stinky Fish",
  "type": "PROTEIN"
}

###








