###Fetch al recent tacos
GET localhost:8080/data-api/tacos?recent

###Fetch taco by id
GET localhost:8080/data-api/tacos/1

###Fetch taco by id which is null
GET localhost:8080/api/tacos/18

###Fetch ingredients
GET localhost:8080/data-api/ingredients

###Fetch ingredient flour tortilla
GET http://localhost:8080/data-api/ingredients/FLTO

###Fetch tacos
GET http://localhost:8080/data-api/tacos

###Fetch tacoes
GET http://localhost:8080/data-api/tacoes

###Lists links for all exposed endpoints
GET http://localhost:8080/data-api

###Fetch first page of tacos where the page size is 5
GET http://localhost:8080/data-api/tacos?size=5

###Fetch second page of tacos by adding the page parameter
GET http://localhost:8080/data-api/tacos?size=5&page=0

###Fetch the 12 most recently created tacos
localhost:8080/data-api/tacos?sort=createdAt,desc&page=0&size=12