# for production need to configure db
#spring:
#  data:
#    mongodb:
#      host: mongodb.tacocloud.com
#      port: 27017
#      username: tacocloud
#      password: s3cr3tp455w0rd
#      database: tacoclouddb
#logging.level.org.springframework.jdbc.core.JdbcTemplate=debug